#!/usr/bin/env bash
cfile="../BDEClustering/res/clustering.properties"
[ $# -gt 0 ] && cfile="$1"

echo "Properties file: $cfile"
java -cp $(cat classpathfile  | tr '\n' ':') gr.demokritos.iit.clustering.exec.BDEEventDetection $cfile
