#! /usr/bin/env bash

BDE_ROOT="$(dirname $(pwd))"
#MAVEN_REPO="$HOME/.m2/repository/"
find "$BDE_ROOT" -iname '*.jar' > temp
#find "$MAVEN_REPO" -iname '*.jar' >> temp

conflictingJars="httpcore-4.1.2.jar httpclient-4.1.2.jar cassandra-driver-core-2.1.7.1.jar guava-14.0.1.jar jersey-server-1.9.jar"
wc -l temp
for confl in $conflictingJars; do
	n1="$(wc -l < temp)"
	cat temp | grep -v $confl > temp2
	cat temp2 > temp
	echo "Dropping $(( $n1 - $(wc -l < temp) )) occurences of $confl"
done

cat temp  > classpathfile
rm temp temp2
wc -l classpathfile
