#!/usr/bin/env bash
cfile="../BDETwitterListener/res/twitter.properties"

[ $# -gt 0 ] && cfile="$1"

echo "Properties file: $cfile"
java -cp $(cat classpathfile | tr '\n' ':') gr.demokritos.iit.crawlers.twitter.CrawlSchedule "$cfile"
