#!/usr/bin/env bash
BDEDIR="../"
cp ./news.properties "$BDEDIR/BDERSSCrawler/res/"
cp ./blogs.properties "$BDEDIR/BDERSSCrawler/res/"
cp ./news.urls "$BDEDIR/BDERSSCrawler/res/"
cp ./blogs.urls "$BDEDIR/BDERSSCrawler/res/"
cp ./clustering.properties "$BDEDIR/BDEClustering/res/"
cp ./location.properties "$BDEDIR/BDELocationExtraction/res/"
cp ./twitter.properties "$BDEDIR/BDETwitterListener/res/"
cp ./twitter.queries "$BDEDIR/BDETwitterListener/res/"
cp ./twitter.accounts "$BDEDIR/BDETwitterListener/res/"
